apiVersion: apps/v1
kind: Deployment
metadata:
  name: istone-backend
  namespace: istone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istone-backend
  template:
    metadata:
      labels:
        app: istone-backend
    spec:
      containers:
      - name: istone-backend-container
        image: public.ecr.aws/y8u8k9s8/team4/istone:backend-1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Port for backend application
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mysql:3306/istdatabase"
        - name: DATABASE_USERNAME
          value: "root"
        - name: DATABASE_PASSWORD
          value: "password"