apiVersion: v1
kind: Service
metadata:
  name: istone-backend-service
  namespace: istone
spec:
  selector:
    app: istone-backend  # Matches the backend pods
  ports:
    - protocol: TCP
      port: 8080  # Port to access the backend internally
      targetPort: 8080  # The port on which the backend container is running # Exposed port on the nodes for external access (optional)
      nodePort: 32222 
  type: NodePort  # Expose the service externally through the node port