apiVersion: apps/v1
kind: Deployment
metadata:
  name: istone-mysql-deployment
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istone-mysql
  template:
    metadata:
      labels:
        app: istone-mysql
    spec:
      containers:
      - name: istone-mysql-container
        image: mysql:8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306  # MySQL port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"  # MySQL root password
        - name: MYSQL_DATABASE
          value: "istdatabase"  # Database name
        - name: MYSQL_USER
          value: "test"  # MySQL username
        - name: MYSQL_PASSWORD
          value: "test"  # MySQL user password