apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: istone
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306  # MySQL port
 # Headless service, allowing direct pod communication