apiVersion: v1
kind: Service
metadata:
  name: istone-frontend-service
  namespace: istone
spec:
  selector:
    app: istone-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
